github.com:
    users:
        magwrap:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: magwrap
